### ISSUE TITLE
Should the mono command be in the path after configuring?

### ISSUE THREAD

**Issue by harrv** [droboports/mono#1]
Thank you for all the work you do to create DroboApps for us. It's very appreciated!

I've noticed that with other DroboApps that configure command-line tools, the command is on the path after configuring, or in other words, the command can be typed and recognized from a command prompt, whether or not you first "cd" to the directory containing the command. For example, after installing python2 on the Drobo 5N, I can type "python" and the Drobo knows what that means. However, after installing mono, the dashboard reports that mono is "configured" but when I type "mono" at a command prompt, it reports that it doesn't know that command. I have to give it the complete path to the command to use it. Is that expected? Is there something I need to do to complete the configuration?

**Comment by ricardopadilha** [comment]
The reason is that the plan for mono is a little more ambitious. I want to use binfmt_misc to eliminate the need to even manually enter mono in the command line. See https://www.kernel.org/doc/Documentation/mono.txt for more information.

**Comment by harrv** [comment]
OK, thanks. Good to know there's a plan. :) I'm interested in Emby and Sonarr, both of which have a mono dependency, I think. My goal is to turn off my Windows computer most of the time, but Besides my Drobo I do have a Raspberry Pi I could run those on for now. Thanks.
